# Generated by Django 5.1.6 on 2025-02-22 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Game name')),
                ('Genre', models.CharField(max_length=60, verbose_name='Game genre')),
                ('regular_price', models.IntegerField(default=0)),
                ('release_date', models.DateField(verbose_name='Release')),
                ('company', models.CharField(default='MiroCoder', max_length=30, verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30, null=True, verbose_name='Address')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('full_name', models.CharField(max_length=255, verbose_name='Name and Surname')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
