# Generated by Django 5.1.6 on 2025-02-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='Genre',
            new_name='genre',
        ),
    ]
