# Generated by Django 5.1.6 on 2025-02-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_games_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'Gamer', 'verbose_name_plural': 'Gamers'},
        ),
    ]
