# Generated by Django 5.1.6 on 2025-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_profilemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='games_lib',
            field=models.ManyToManyField(blank=True, to='mainapp.games'),
        ),
        migrations.AlterField(
            model_name='games',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
