# Generated by Django 5.1.6 on 2025-02-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_profilemodel_games_lib_alter_games_regular_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='Game Image'),
        ),
    ]
